In [5]:
import pandas as pd

df=pd.read_csv("data/统计数据.csv",encoding="gbk")
#读取cvs：中文通常是GBK编码，用utf—8会报错
df

,地区,地区生产总值(亿元),一般预算收入(亿元),商品房平均销售价格(元/平方米),颗粒物排放量(万吨),每十万人高校在校生数,医疗卫生机构床位数(万张)
0,北京市,41610.9,5714.36,38240,0.41,5397,13.39
1,天津市,16311.3,1846.69,15572,0.90,5428,6.85
2,河北省,42370.4,4056.30,8021,23.65,3070,48.57
3,山西省,25642.6,3453.99,6713,26.63,3388,22.84
4,内蒙古自治区,23158.6,2824.39,6288,99.30,2493,16.77
5,辽宁省,28975.1,2525.07,8315,21.77,3931,32.62
6,吉林省,13070.2,851.00,6955,16.61,4989,17.72
7,黑龙江省,15901.0,1290.66,6152,34.76,3734,26.13
8,上海市,44652.8,7608.00,40302,0.83,3756,16.53
9,江苏省,122875.6,9258.88,12226,9.09,3726,56.30
10,浙江省,77715.4,8039.85,18576,6.61,2763,38.17
11,安徽省,45045.0,3589.14,7637,9.73,3283,44.40
12,福建省,53109.9,3339.21,10771,7.98,3277,23.24
13,江西省,32074.7,2948.33,7318,10.68,4423,31.45
14,山东省,87435.1,7104.10,8393,19.11,3663,69.36
15,河南省,61345.1,4250.35,6133,6.96,3652,75.22
16,湖北省,53734.9,3281.13,8553,12.70,4110,45.03
17,湖南省,48670.4,3101.76,6372,12.89,3738,54.45
18,广东省,129118.6,13260.88,14985,13.40,3129,60.83
19,广西壮族自治区,26300.9,1687.72,5473,7.11,3651,34.17
20,海南省,6818.2,832.43,17050,0.75,2999,6.12
21,重庆市,29129.0,2103.42,7132,4.98,3838,25.08
22,四川省,56749.8,4880.55,8153,15.19,3127,68.39
23,贵州省,20164.6,1886.41,5799,9.26,2608,30.97
24,云南省,28954.2,1949.46,6804,24.43,3097,34.12
25,西藏自治区,2132.6,179.63,8510,0.73,1666,2.00
26,陕西省,32772.7,3311.57,9884,21.08,4409,28.96
27,甘肃省,11201.6,907.65,5682,12.14,3215,18.89
28,青海省,3610.1,329.10,7093,4.99,1738,4.29
29,宁夏回族自治区,5069.6,460.15,7016,5.83,3271,4.18
30,新疆维吾尔自治区,17741.3,1889.76,5827,52.90,2773,17.96

In [7]:
df.head()#看前五行

,地区,地区生产总值(亿元),一般预算收入(亿元),商品房平均销售价格(元/平方米),颗粒物排放量(万吨),每十万人高校在校生数,医疗卫生机构床位数(万张)
0,北京市,41610.9,5714.36,38240,0.41,5397,13.39
1,天津市,16311.3,1846.69,15572,0.90,5428,6.85
2,河北省,42370.4,4056.30,8021,23.65,3070,48.57
3,山西省,25642.6,3453.99,6713,26.63,3388,22.84
4,内蒙古自治区,23158.6,2824.39,6288,99.30,2493,16.77

In [8]:
df.shape#看规模（行数，列数）=31个省7个指标

(31, 7)

In [9]:
df.info()#看类型和缺失1. Non-Null Count非空值个数31 non-null = 没有缺失值   2.Dtype数据类型 object=文字，float64=小数，int64=整数

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   地区                31 non-null     object
 1   地区生产总值(亿元)        31 non-null     float64
 2   一般预算收入(亿元)        31 non-null     float64
 3   商品房平均销售价格(元/平方米)  31 non-null     int64
 4   颗粒物排放量(万吨)        31 non-null     float64
 5   每十万人高校在校生数        31 non-null     int64
 6   医疗卫生机构床位数(万张)     31 non-null     float64
dtypes: float64(4), int64(2), object(1)
memory usage: 1.8+ KB

In [10]:
df.describe()#数值列的统计摘要 1.count非空个数 2.mean平均值 3.std标准差 4.min/max 5.25%，50%，75%四分位数50%是中位数

,地区生产总值(亿元),一般预算收入(亿元),商品房平均销售价格(元/平方米),颗粒物排放量(万吨),每十万人高校在校生数,医疗卫生机构床位数(万张)
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,38821.361290,3508.449677,10707.903226,15.916129,3494.903226,31.451613
std,31350.734213,2945.094210,8369.586399,19.143210,868.919419,20.443641
min,2132.600000,179.630000,5473.000000,0.410000,1666.000000,2.000000
25%,17026.300000,1767.205000,6542.500000,6.220000,3083.500000,17.245000
50%,29129.000000,2948.330000,7637.000000,10.680000,3388.000000,28.960000
75%,50890.150000,4153.325000,10327.500000,20.095000,3797.000000,44.715000
max,129118.600000,13260.880000,40302.000000,99.300000,5428.000000,75.220000